### ISSUE TITLE
Can't install nuget on .net fx 4.5

### ISSUE THREAD

**Issue by thangtx** [gravity00/SimpleSOAPClient#20]
Hi graty00
When I install from nuget, it throw this error:
PM> Install-Package SimpleSOAPClient -Pre
Attempting to gather dependencies information for package 'SimpleSOAPClient.2.0.0-rc03' with respect to project 'TranzwareAPI', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'SimpleSOAPClient.2.0.0-rc03' with DependencyBehavior 'Lowest'
Resolving actions to install package 'SimpleSOAPClient.2.0.0-rc03'
Resolved actions to install package 'SimpleSOAPClient.2.0.0-rc03'
Adding package 'SimpleSOAPClient.2.0.0-rc03' to folder 'D:\Windows7\TranzwareAPI\packages'
Added package 'SimpleSOAPClient.2.0.0-rc03' to folder 'D:\Windows7\TranzwareAPI\packages'
Install failed. Rolling back...
Package 'SimpleSOAPClient 2.0.0-rc03' does not exist in project 'TranzwareAPI'
Removing package 'SimpleSOAPClient 2.0.0-rc03' from folder 'D:\Windows7\TranzwareAPI\packages'
Removed package 'SimpleSOAPClient 2.0.0-rc03' from folder 'D:\Windows7\TranzwareAPI\packages'
Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ Install-Package SimpleSOAPClient -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by gravity00** [comment]
This is related with issue #17 
Next release will have the dependencies marked as build and this should stop from happening.
