### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by NoCodeMonkey** [gravity00/SimpleSOAPClient#22]
Hi,

I keep getting a NullReferenceException exception when I use the DelegatingSoapHandler.

System.NullReferenceException: Object reference not set to an instance of an object.
   at SimpleSOAPClient.Handlers.DelegatingSoapHandler.<OnSoapEnvelopeResponseAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SimpleSOAPClient.SoapClient.<RunAfterSoapEnvelopeDeserializationHandler>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleSOAPClient.SoapClient.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

`.WithHandler(new DelegatingSoapHandler
                {
                    Order = int.MaxValue, // Will be the last handler before the request and the first after the response
                    OnHttpRequestAsyncAction = async (c, args, cnt) =>
                    {
                        Logger.Trace(
                            "SOAP Outbound Request [{0}] -> {1} {2}({3})\n{4}",
                            args.TrackingId, args.Request.Method, args.Url, args.Action,
                            await args.Request.Content.ReadAsStringAsync());
                    },
                    OnHttpResponseAsyncAction = async (c, args, cnt) =>
                    {
                        Logger.Trace(
                            "SOAP Outbound Response [{0}] -> {1}({2}) {3} {4}\n{5}",
                            args.TrackingId, args.Url, args.Action, (int)args.Response.StatusCode,
                            args.Response.StatusCode, await args.Response.Content.ReadAsStringAsync());
                    }
                })`

Without it, everything runs fine.

**Comment by gravity00** [comment]
Based on the code from that release, it looks everything is ok and my testings can't replicate your behavior. Can you check if any of the properties you are using inside lambdas are not null, specially `args.Response.Content`? The server may be returning an HTTP 5xx without a body and that property may be null.

What I wan't to check is if the code is failing before invoking your actions or is are inside them (and I'll also need to update my examples if that's the case).

**Comment by NoCodeMonkey** [comment]
Hi,

You are right, it looks like there is an await null somewhere. For reference I am using version 2.0.0-rc03 and the .net 4.52 framework. Something as simple as the following still throws the exception:
`
OnHttpRequestAsyncAction = async (c, args, cnt) =>
{
	Logger.Trace("Request");
},
OnHttpResponseAsyncAction = async (c, args, cnt) =>
{
	Logger.Trace("Response");
)`

Cheers

**Comment by gravity00** [comment]
Hi,

I'm still failing to replicate the problem. I created an old project with 4.5.2 framework, included the NuGet 1.0.0-rc03 and only adding a `DelegatingSoapHandler` with only those actions runs normally as expected.
Can you supply an example code about how you are using the client?

> Note: tomorrow I should be able so release RC04 that brings some fixes and support for SOAP 1.2. Eventually any problem may be fixed there.

**Comment by NoCodeMonkey** [comment]
Hi,

Found it. It is pointing to the delegate and not the invoke. See DelegatingSoapHandler OnSoapEnvelopeResponseAsync method.

if (OnSoapEnvelopeResponseAsyncAction == null)
	OnSoapEnvelopeResponseAction(client, arguments);
else
	await OnSoapEnvelopeResponseAsyncAction(client, arguments, ct);`

if (OnSoapEnvelopeResponseAsyncAction == null)
	OnSoapEnvelopeResponse(client, arguments); 
else
	await OnSoapEnvelopeResponseAsyncAction(client, arguments, ct);

Cheers

**Comment by gravity00** [comment]
Hi,

Great finding @NoCodeMonkey! The next release will have that fixed since I changed the logic to make sure both async and sync logic is invoked for a given handler (see #21). Until I release RC04 you'll have to assign that handler with an action that does nothing to prevent the null exception.

I'll close this issue when RC04 is released. Thanks.

**Comment by Noahan** [comment]
Hello, when version RC04 will be release? I have that same problem :(

**Comment by gravity00** [comment]
@NoCodeMonkey  [Version 2.0.0-rc04](https://www.nuget.org/packages/SimpleSOAPClient/2.0.0-rc04) has been released and includes this fix.
