### ISSUE TITLE
How to use SimpleSOAPClient to consume Web Service (asmx)  from .NET Core Web API?

### ISSUE THREAD

**Issue by udkadam** [gravity00/SimpleSOAPClient#27]
We are currently working over WEBAPI in ASP.NET core. Our requirement is to consume .NET based Webservice (asmx) from Web API.

I have web service method which has two input parameters. 

GetEmployees(string name,string department)

How should I move ahead ? 

I tried your example code but its giving me some issues.

Please help.

**Comment by gravity00** [comment]
Hi @udkadam, 

Can you give me a sample code? 
Because, for the moment, I don't have a way to automatically generate all the requests based on a WSDL, the easiest approach is to use a client like SoapUI and be sure you are creating the envelope correctly.

**Comment by gravity00** [comment]
Closing due to missing feedback.
