### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Noahan** [gravity00/SimpleSOAPClient#29]
Hi, in nuget currently is 2.0.0 RC3 version in DEBUG Mode?
I use your solution in my uwp application and i need Release mode. When you plan to sent new version of SimpleSOAPClient (Release Mode) to nuget repository?

**Comment by gravity00** [comment]
@Noahan why do you say it is in DEBUG mode? Are you talking about a final version?

**Comment by Noahan** [comment]
I downloaded "SimpleSOAPClient" using nuget, and i have problem with publishing application because SimpleSOAPClient.dll file was build using DEBUG MODE.

Error from windows store audit "The binary SimpleSOAPClient.dll is built in debug mode."

![image](https://cloud.githubusercontent.com/assets/19434299/26497189/ccc0d704-422a-11e7-8d7b-68ebf6ea9a73.png)

For build my uwp application i using Release Mode and that dll is in "\obj\x86\Release\ilc\in\SimpleSOAPClient.dll"

**Comment by gravity00** [comment]
That's strange, it should have been compiled in release mode, but I'll give it a look.

I'm making some major refactoring changes, once the delay in the final release, but I can make a sooner release just to solve this problem and some minor bugs I found.

**Comment by gravity00** [comment]
@Noahan I just released [version 2.0.0-rc04](https://www.nuget.org/packages/SimpleSOAPClient/2.0.0-rc04) that is compiled in release mode as expected. Can you give it a try?
