### ISSUE TITLE
Usage in a Xamarin.Forms projects

### ISSUE THREAD

**Issue by nicolabeghin** [gravity00/SimpleSOAPClient#31]
Hi everyone
I'm trying to use this library in a Xamarin.Forms project.
Specifically, I tried:

**PCL project**, referenced from Xamarin.Android + Xamarin.UWP project => strange invocation issues arises
![image 4](https://user-images.githubusercontent.com/2743637/27948836-8d86e37a-62fb-11e7-9d9f-5e1717b0a633.png)

**Xamarin.Android** project only (unable to install nuget)
![image 3](https://user-images.githubusercontent.com/2743637/27948786-5de0e22e-62fb-11e7-9ed8-5d11731ea624.png)

Is this supposed to happen or am I doing something wrong? 

thanks
nicola

**Comment by nicolabeghin** [comment]
I tried with stable version too, same error in Xamarin.Android project.

![image 6](https://user-images.githubusercontent.com/2743637/27949827-774c25c6-62ff-11e7-8368-288db7a744d7.png)

**Comment by gravity00** [comment]
Do you have the most recent NuGet version installed (https://dist.nuget.org/index.html)?

**Comment by nicolabeghin** [comment]
I moved to Visual Studio 2017, so it should have the latest nuget available. I'm no C# expert (I have strong Java background), maybe I'm missing something!

**Comment by nicolabeghin** [comment]
thanks a lot @gravity00 !! I'll check it out tomorrow, as yesterday I imported the whole source code and compiled from my project itself, without using nuget. Is the updated nuget package already available?

**Comment by gravity00** [comment]
I just released [version 2.0.0-rc04](https://www.nuget.org/packages/SimpleSOAPClient/2.0.0-rc04), that should have this problem fixed. Can you give it a test?

**Comment by gravity00** [comment]
@nicolabeghin should be indexed by NuGet in a few minutes.

**Comment by nicolabeghin** [comment]
@gravity00 I confirm issue is fixed with latest release 2.0.0-rc04
