### ISSUE TITLE
The methods used in the sample are absent

### ISSUE THREAD

**Issue by stepurich** [gravity00/SimpleSOAPClient#33]
Hello,
I can’t run [the sample](https://github.com/gravity00/SimpleSOAPClient#usage-version-200-rc01) in any way. The methods used in it are not found in the source code.

I work around these problems but I still haven’t been able to assign my header for the envelope.

What am I doing wrong?

I'm trying to use the SimpleSoapClient in a .NETCoreApp 1.1 project

**Comment by gravity00** [comment]
Hey there,

Those methods are extensions. Have you included the helpers namespace? 
```csharp
using SimpleSOAPClient.Helpers;
```

**Comment by stepurich** [comment]
Thanks a lot for the answer. I do not know why I could not find these extensions myself and VS did not prompt me.

**Comment by stepurich** [comment]
I'm wrong, VS prompts. It was my fault only.

**Comment by gravity00** [comment]
All right. Done then :)
