### ISSUE TITLE
EnvelopeHelpers.Body skips Namespace information

### ISSUE THREAD

**Issue by szogun1987** [gravity00/SimpleSOAPClient#35]
If I there is a class
```
[XmlRoot("SomeMessage", Namespace= "http://foo.com")]
public class Message
{
     [XmlElement("field")]
    public string Property { get;set; }
}
```
and then I I will execute
```
var envelope = SoapEnvelope
    .Prepare()
    .Body(new Message { Property = "bar" });
await client.SendAsync("someUrl", "someAction", envelope);
```
sent message would look like this
```
<q1:Envelope xmlns:q1="http://schemas.xmlsoap.org/soap/envelope/">
    <q1:Header/>
    <q1:Body>
        <q1:SomeMessage>
             <q1:field>bar</q1:field>
        </q1:SomeMessage>
    </q1:Body>
<q1:Envelope>
```
but it should look like this

```
<q1:Envelope xmlns:q1="http://schemas.xmlsoap.org/soap/envelope/">
    <q1:Header/>
    <q1:Body>
        <q2:SomeMessage xmlns:q2="http://foo.com">
             <q2:field>bar</q2:field>
        </q2:SomeMessage>
    </q1:Body>
<q1:Envelope>
```
It is caused by using EmptyXmlSerializerNamespaces  in XmlHelpers

**Comment by tunurgitr** [comment]
This one is pretty critical for me, so if there's anything I can do to help, let me know.

**Comment by szogun1987** [comment]
Hi @tunurgitr 
As a workaround you can copy [mine implementation of ToXElement method](https://github.com/szogun1987/profil-zaufany-dotnet-core/blob/master/src/ProfilZaufany/Helpers/XmlHelpers.cs) you can call Body method and pass result of mine implementation to it.

**Comment by gravity00** [comment]
@tunurgitr @tunurgitr sorry guys, it has been some busy weeks, but I'll give it a big look today, and will release a fix soon. Thanks for the reminder!

**Comment by gravity00** [comment]
@szogun1987 @tunurgitr after some testings I realized the problem wasn't the `Body` method but with the serialization provider himself. Some time ago I made some refactoring to the serializer and introduced the problem. The fastest solution is to include the envelope namespace into the serialization provider, like this:

```csharp
//  cast to default implementation
var provider = (SoapEnvelopeSerializationProvider) SoapClientSettings.Default.SerializationProvider;
//  this will add the missing namespace
provider.XmlSerializerNamespaces.Add("SOAP-ENV", Constant.Namespace.OrgXmlSoapSchemasSoapEnvelope);
```
The `SoapClient` constructor can also receive it's own settings instead of using the global one, to prevent side effects.

Example code to validate the solution:
```csharp
    public static class Program
    {
        static void Main(string[] args)
        {
            var provider = (SoapEnvelopeSerializationProvider) SoapClientSettings.Default.SerializationProvider;
            provider.XmlSerializerNamespaces.Add("SOAP-ENV", Constant.Namespace.OrgXmlSoapSchemasSoapEnvelope);

            //  just for readability purposes
            provider.XmlWriterSettings.Indent = true;

            using (var client = SoapClient.Prepare().WithHandler(new DelegatingSoapHandler
            {
                OnHttpRequestAsyncAction = async (c, arg, ct) =>
                {
                    var envelopeXml = await arg.Request.Content.ReadAsStringAsync();
                    /*
                    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
                      <SOAP-ENV:Header />
                      <SOAP-ENV:Body>
                        <q1:SomeMessage xmlns:q1="http://foo.com">
                          <q1:field>bar</q1:field>
                        </q1:SomeMessage>
                      </SOAP-ENV:Body>
                    </SOAP-ENV:Envelope>
                    */
                }
            }))
            {
                client.Send("someUrl", "someAction", SoapEnvelope
                    .Prepare()
                    .Body(new Test02.Message
                    {
                        Property = "bar"
                    }));
            }
        }
    }
```
*Note:* this still needs further investigation before releasing a fix because I can't detect this behavior in our production environments or when testing with more complex entities.

**Comment by iby-dev** [comment]
I definitely ran into this issue the code sample above definitely helped.

This package is a good alternative for netcore and traditional wcf usage.

Looking forward to seeing any updates in this space.

**Comment by gravity00** [comment]
@iby-dev version 2.1.0 now also [supports data contracts](https://github.com/gravity00/SimpleSOAPClient/pull/38), does the problem still persists if you use them?

I'm now working in a major release that I hope to simplify even more this library usage and removing also this bug (I still find it strange to only happen in very simple entities).

**Comment by iby-dev** [comment]
Hi, it did for but then I used the code you provided and in it all started working. I will share a complete code sample once i have it all working together.
