### ISSUE TITLE
Cannot publish Console app as executable if it depends on SimpleSoapClient

### ISSUE THREAD

**Issue by szogun1987** [gravity00/SimpleSOAPClient#37]
If I try to run 
```dotnet publish --configuration Release --self-contained --runtime win-x64```
Lot of errors similar to:
```Mine.Internal.Library.csproj : error NU1605:  Mine.Internal.Library -> ProfilZaufany 1.0.3-alpha -> SimpleSOAPClient.BinarySecurityToken 1.0.2-alpha -> SimpleSOAPClient 2.0.0-rc04 -> System.Xml.XmlSerializer 4.0.11 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)```
appears.
I'm trying to build .net standard 2.0 app.

**Comment by szogun1987** [comment]
I was able to get following error also
```Zeto.PlatformaZamowienPublicznych.Core.csproj: [NU1605] Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
Mine.Internal.Library -> ProfilZaufany 1.0.3-alpha -> SimpleSOAPClient.BinarySecurityToken 1.0.2-alpha -> SimpleSOAPClient 2.0.0-rc04 -> System.Net.Http 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
Mine.Internal.Library-> ProfilZaufany 1.0.3-alpha -> SimpleSOAPClient.BinarySecurityToken 1.0.2-alpha -> SimpleSOAPClient 2.0.0-rc04 -> System.Net.Http 4.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)
```

**Comment by szogun1987** [comment]
Unfortunately I cannot reproduce it with sample aside project, but I found out that if I rebuild SimpleSOAPClient manually and used build assembly instead of version from Nuget it works. Can you Rebuild and publish new version on Nuget?

**Comment by gravity00** [comment]
Let me give it a try to see were the problem may be

**Comment by szogun1987** [comment]
There is a chance that adding netstandard as target platform would help. Library I used was built this way.

**Comment by gravity00** [comment]
@szogun1987  The library is referencing .NET Standard 1.1 (and others). It shouldn't have any problem being referenced by a .NET Standard 2.0 project.
Just created a VS 2017 project, with a console (NET Core App 2.0) referencing a lib (.NET Standard 2.0), which is referencing both `SimpleSOAPClient` and `SimpleSOAPClient.BinarySecurityToken` and it successfully compiled as a self contained console: `dotnet publish --configuration Release --self-contained --runtime win-x64`

Can you send me an example project with the problem?

Test app: [SimpleSOAPClientIssues37.zip](https://github.com/gravity00/SimpleSOAPClient/files/1889246/SimpleSOAPClientIssues37.zip)

**Comment by szogun1987** [comment]
When I tried to create aside project that references same chain of projects I was able to publish it also. I will try to find something in my project. If I copied dll from package manually It worked also.

**Comment by szogun1987** [comment]
SimpleSOAPClient is somehow conflicted with FluentValidation. Simplest csproj files where issue is reproducible looks like this:
```<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="7.5.2" />
    <PackageReference Include="SimpleSOAPClient" Version="2.0.0-rc04" />
  </ItemGroup>

</Project> 
```

**Comment by gravity00** [comment]
@szogun1987 Like the errors says, it is detecting a downgrade is some of the referenced packages. Both `SimpleSOAPClient` and `FluentValidation` are directly referencing the library NuGets instead of the aggregation `NETStandard.Library`. When I started this library that wasn't the norm yet (as an example, VS2017 now automatically references that dependency) and that's the reason for the direct references, but I'll change it in the next release.

I'm not sure if this may be a NuGet or dotnet bug, because it should detect and use the most recent versions, but it strangely only affects when making a publish.

For now, my suggestion to fix your problem is to manually add the dependencies using the most recent version (needed by `FluentValidation`):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="7.5.2" />
    <PackageReference Include="SimpleSOAPClient" Version="2.0.0-rc04" />
    <PackageReference Include="SimpleSOAPClient.BinarySecurityToken" Version="1.0.1" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
  </ItemGroup>

</Project>

```

**Comment by szogun1987** [comment]
Great it is working 👍  mark this issue as solved. I'm waiting for next release
