### ISSUE TITLE
Cannot Debug Code with sample Usage

### ISSUE THREAD

**Issue by ertemmstein** [gravity00/SimpleSOAPClient#39]
Hello , 

When i try to Debug with sample Usage on main page it gives an error:
_" SoapClient' does not contain a definition for 'OnSerializeRemoveXmlDeclaration' and no extension method 'OnSerializeRemoveXmlDeclaration' accepting a first argument of type 'SoapClient' could be found"_

What did i miss? The project is  .Net Core 2.0 based

**Comment by gravity00** [comment]
Hey,

You are correct. I made some breaking changes between release candidates and forgot to update the documentation. Just updated using version `2.0.0`.
