### ISSUE TITLE
OASIS WS Header

### ISSUE THREAD

**Issue by MikelThief** [gravity00/SimpleSOAPClient#42]
Hello, I would like to contribute by adding support for WS Security with UserNameToken, Password Digest and NONCE. Which branch should i choose as a base?

**Comment by gravity00** [comment]
Hi @MikelThief 

Thanks for the future contribution.
Since I'm analyzing some breaking changes for v3, I recommend using the branch **Release-v2.x**.

**Comment by MikelThief** [comment]
Thanks for information :)

**Comment by skynode** [comment]
Hey @MikelThief, are you still working on this feature?

**Comment by MikelThief** [comment]
@skynode indeed. I have completed the classes that allowed me to perform a handshake with this type of WS-Security protected webservice. I had no time to integrate it into this project. I was put into another case straight after finishing it... I can share those classes with you. I will try to find time to make a pull request as this issue patiently hangs on my github dashboard ;)
