### ISSUE TITLE
SoapEnvelopeDeserializationException: The response content is empty

### ISSUE THREAD

**Issue by etosson** [gravity00/SimpleSOAPClient#45]
Hi,

I keep getting a 
{SimpleSOAPClient.Exceptions.SoapEnvelopeDeserializationException: The response content is empty.
   at SimpleSOAPClient.SoapClient.SendAsync(String url, String action, SoapEnvelope requestEnvelope, CancellationToken ct)
   at TestWCFBinding.Controllers.ValuesController.Get()}

![image](https://user-images.githubusercontent.com/11943772/51383095-8fb31c80-1b29-11e9-810b-2057b374a771.png)

and this is my simple wcf operation 

        [OperationContract]
        bool IsAlive();

please advise,
thanks

**Comment by gravity00** [comment]
Hi @etosson 

Looking at your error message it seems nothing is being returned from the server.
Can you provide some request and response log using Fiddler os something similar?
You can also use the SimpleSOAPClient HTTP interceptors to trace and debug your requests:

```csharp
                OnHttpRequestAsyncAction = async (soapClient, d, cancellationToken) =>
                {
                    Logger.LogTrace(
                        "SOAP Outbound Request -> {0} {1}({2})\n{3}",
                        d.Request.Method, d.Url, d.Action, await d.Request.Content.ReadAsStringAsync());
                },
                OnHttpResponseAsyncAction = async (soapClient, d, cancellationToken) =>
                {
                    Logger.LogTrace(
                        "SOAP Outbound Response -> {0}({1}) {2} {3}\n{4}",
                        d.Url, d.Action, (int) d.Response.StatusCode, d.Response.StatusCode,
                        await d.Response.Content.ReadAsStringAsync());
                },
```

**Comment by gravity00** [comment]
Now that I look better, it seems you are also passing the address as the action parameter. That should be the problem.

**Comment by etosson** [comment]
Thanks João for the quick reply. I changed the action name, but still, gives me the same exception.
The response of the WCF operation is just "true" value (just for testing).

![image](https://user-images.githubusercontent.com/11943772/51437941-683d8a80-1cb6-11e9-85a7-285b57c29d65.png)

I think the connection between client and server couldn't be instantiated. do you advise any binding configuration or something like that?

Thanks,

**Comment by etosson** [comment]
This is the operation:
![image](https://user-images.githubusercontent.com/11943772/51438066-39c0af00-1cb8-11e9-8345-a5beb366d232.png)

& the binding: 
![image](https://user-images.githubusercontent.com/11943772/51438082-696fb700-1cb8-11e9-8ccc-e8f24b080f0f.png)

**Comment by gravity00** [comment]
Looking at those WCF settings, it seems you are using a secure binding, but from the sample code you are invoking an HTTP endpoint.
Can you inspect the requests and responses using Fiddler an post that information here?

**Comment by etosson** [comment]
Ok, Mr. João, so how I invoke this WCF service (IsAlive) using this type of binding (TransportWithMessageCredential)? this is what I need actually. which .net core fails with this type of binding.

Thanks so much for your support.

**Comment by gravity00** [comment]
For this case, I'm assuming the example in the readme should suffice. Change the protocol to https instead of http, and include the SOAP header for username and password either by adding on every request or just for this envelope.

Here's the simplified version:

```csharp
public static async Task MainAsync(string[] args, CancellationToken ct)
{
    using (var client =
        SoapClient.Prepare()
            .WithHandler(new DelegatingSoapHandler
            {
                OnSoapEnvelopeRequestAsyncAction = async (c, d, cancellationToken) =>
                {
                    d.Envelope.WithHeaders(
                        KnownHeader.Oasis.Security.UsernameTokenAndPasswordText(
                            "some-user", "some-password"));
                }
            }))
    {
        var requestEnvelope =
            SoapEnvelope.Prepare().Body(new IsAliveRequest());

        SoapEnvelope responseEnvelope
                await client.SendAsync(
                    "https://services.company.com/Service.svc",
                    "http://services.company.com/IService/IsAlive",
                    requestEnvelope, ct);
    }
}
```
