### ISSUE TITLE
Support for .net core 2.2

### ISSUE THREAD

**Issue by andersmandersen** [gravity00/SimpleSOAPClient#47]
Hi,

Are there anyways to use this module for .net core 2.2? Can I just download the source code and compile it to 2.2 myself?

**Comment by gravity00** [comment]
Hi @andersmandersen 

The [NuGet](https://www.nuget.org/packages/SimpleSOAPClient/) does support .NET Standard 2.0, so it's compatible with .NET Core 2.2. Are you facing any problem including it in your solution?

**Comment by andersmandersen** [comment]
Hi,

Sorry. It wasn't a problem with your package but my visual studio, that for some reason didn't detch any .net core version.
