### ISSUE TITLE
Soap message response with bytes

### ISSUE THREAD

**Issue by ilCosmico** [gravity00/SimpleSOAPClient#50]
Hi there,

I'm trying to use this amazing library for a project that I'm converting from .NET Framework to .NET6.
I'm able to communicate with the original WebService, but the current client (I mean the one done in .NET Framework) returns a byte[] instead of an XmlNode[].

Could you help me to handle this, please?

**Comment by gravity00** [comment]
hi @ilCosmico,

When you say it returns a `byte[]` instead of a `XmlNode[]`, do you mean some property or the full content of the soap message is serialized as a `byte[]`? Can you give more detail?

**Comment by ilCosmico** [comment]
Hi @gravity00,

Here you can see results (in bytes) that I get from the original code.
![image](https://user-images.githubusercontent.com/8678145/155678469-4c1034bb-d1bc-4188-a149-02f168a831ee.png)

And here you can see results (XML nodes) that I get with this library
![image](https://user-images.githubusercontent.com/8678145/155678489-910fe76b-18f3-47ad-82d0-e12b86c6f560.png)

I don't know if this can help you to better understand, but listen below you can see the attributes used for the method in the original code.
`[System.Web.Services.Protocols.SoapDocumentMethodAttribute( "http://www.xxxxxxxxx/Dispatch", RequestNamespace="http://www.xxxxxxxxx", ResponseNamespace="http://www.xxxxxxxxx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped )]`

And here is how I defined the class for the web service response

```
[XmlRoot("DispatchResponse", Namespace = "http://www.xxxxxxxxx")]
public class DispatchResponse
{
	[XmlElement("DispatchResult")]
	public object[] DispatchResult { get; set; }			
}
```

**Comment by gravity00** [comment]
From what I'm understanding, the property `DispatchResult` should be defined as a `byte[]` because it seems that's what the service is returning, encoded as a base 64 string. Does this work?

```csharp
[XmlRoot("DispatchResponse", Namespace = "http://www.xxxxxxxxx")]
public class DispatchResponse
{
    [XmlElement("DispatchResult")]
    public byte[] DispatchResult { get; set; }			
}
```

If not, you could define it as a string and manually use `Convert.FromBase64String(response.DispatchResult)` to get the array.

**Comment by ilCosmico** [comment]
Yep! Thanks for your great support!

![image](https://user-images.githubusercontent.com/8678145/155706415-5f3305ac-e053-4228-b38b-9690d044a034.png)
